version: '3.8'
services:
  api:
    image: lucasbschuck/user-devops-api:latest
    container_name: user-devops-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://${RDS_ENDPOINT}:5432/userdb
    - SPRING_DATASOURCE_USERNAME=${RDS_USERNAME}
    - SPRING_DATASOURCE_PASSWORD=${RDS_PASSWORD}
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update