spring:
  application:
    name: user-devops
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: lucas
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  web:
    error:
      include-stacktrace: never