spring:
  application:
    name: user-devops
  config:
    import: "aws-parameterstore:/devops-portfolio/db/"
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/userdb
    username: lucas
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        auto: validate
  web:
    error:
      include-stacktrace: never