spring:
  application:
    name: user-devops
  config:
    import: "aws-parameterstore:/devops-portfolio/db/"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
management:
    endpoints:
      web:
        exposure:
          include: health,info,prometheus
    endpoint:
      prometheus:
        enabled: true
    metrics:
      tags:
        application: ${spring.application.name}